apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-api
    labels:
        app: auth-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth-api
    template:
        metadata:
            labels:
                app: auth-api
        spec:
            containers:
                - name: auth-api
                  image: lavorocontainers.azurecr.io/auth-api:<tag>
                  ports:
                      - containerPort: 80
                  env:
                      - name: SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: secret-key
                                key: SECRET_KEY
                      - name: DB_CONNECTION_STRING
                        valueFrom:
                            secretKeyRef:
                                name: db-connection-string
                                key: DB_CONNECTION_STRING
                      - name: EMAIL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: email-password
                                key: EMAIL_PASSWORD
                      - name: STREAM_CHAT_API_KEY
                        valueFrom:
                            secretKeyRef:
                                name: stream-chat-api-key
                                key: STREAM_CHAT_API_KEY
                      - name: STREAM_CHAT_API_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: stream-chat-api-secret
                                key: STREAM_CHAT_API_SECRET
